//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework4.EIS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.radford.edu/EWS", ConfigurationName="EIS.EmpInfoServiceSoap")]
    public interface EmpInfoServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/getEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Homework4.EIS.Employee getEmployee(string EIN, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/getEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<Homework4.EIS.Employee> getEmployeeAsync(string EIN, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/saveEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saveEmployee(Homework4.EIS.Employee EmployeeToSave, string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/saveEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<string> saveEmployeeAsync(Homework4.EIS.Employee EmployeeToSave, string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/saveNewEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saveNewEmployee(Homework4.EIS.Employee EmployeeToSave, string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/saveNewEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<string> saveNewEmployeeAsync(Homework4.EIS.Employee EmployeeToSave, string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/deleteEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string deleteEmployee(string strEIN, string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/deleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<string> deleteEmployeeAsync(string strEIN, string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/getEmployeesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getEmployeesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/getEmployeesList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getEmployeesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/getStatesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getStatesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/getStatesList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getStatesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/logIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string logIn(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/logIn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> logInAsync(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/logOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string logOut(string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/logOut", ReplyAction="*")]
        System.Threading.Tasks.Task<string> logOutAsync(string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/getDeptList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getDeptList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/getDeptList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDeptListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/changePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string changePassword(string username, string pw, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/EWS/changePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> changePasswordAsync(string username, string pw, string token);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/EWS")]
    public partial class Employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eINField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleInitialField;
        
        private string sSNField;
        
        private string homePhoneField;
        
        private string workPhoneField;
        
        private string cellPhoneField;
        
        private string officeLocationField;
        
        private string streetAddressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private System.DateTime dateHiredField;
        
        private string deptCodeField;
        
        private System.DateTime dateOfBirthField;
        
        private int taxExemptionsField;
        
        private string taxFilingStatusField;
        
        private decimal extraWithholdingsField;
        
        private System.DateTime dateOfLastRaiseField;
        
        private string employeeTypeField;
        
        private decimal salaryOrWageField;
        
        private string titleField;
        
        private string genderField;
        
        private string supervisorEINField;
        
        private string constructorMessageField;
        
        private int revNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EIN {
            get {
                return this.eINField;
            }
            set {
                this.eINField = value;
                this.RaisePropertyChanged("EIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MiddleInitial {
            get {
                return this.middleInitialField;
            }
            set {
                this.middleInitialField = value;
                this.RaisePropertyChanged("MiddleInitial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
                this.RaisePropertyChanged("SSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("HomePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
                this.RaisePropertyChanged("WorkPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CellPhone {
            get {
                return this.cellPhoneField;
            }
            set {
                this.cellPhoneField = value;
                this.RaisePropertyChanged("CellPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OfficeLocation {
            get {
                return this.officeLocationField;
            }
            set {
                this.officeLocationField = value;
                this.RaisePropertyChanged("OfficeLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StreetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
                this.RaisePropertyChanged("StreetAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime DateHired {
            get {
                return this.dateHiredField;
            }
            set {
                this.dateHiredField = value;
                this.RaisePropertyChanged("DateHired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DeptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
                this.RaisePropertyChanged("DeptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int TaxExemptions {
            get {
                return this.taxExemptionsField;
            }
            set {
                this.taxExemptionsField = value;
                this.RaisePropertyChanged("TaxExemptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TaxFilingStatus {
            get {
                return this.taxFilingStatusField;
            }
            set {
                this.taxFilingStatusField = value;
                this.RaisePropertyChanged("TaxFilingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal ExtraWithholdings {
            get {
                return this.extraWithholdingsField;
            }
            set {
                this.extraWithholdingsField = value;
                this.RaisePropertyChanged("ExtraWithholdings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime DateOfLastRaise {
            get {
                return this.dateOfLastRaiseField;
            }
            set {
                this.dateOfLastRaiseField = value;
                this.RaisePropertyChanged("DateOfLastRaise");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string EmployeeType {
            get {
                return this.employeeTypeField;
            }
            set {
                this.employeeTypeField = value;
                this.RaisePropertyChanged("EmployeeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal SalaryOrWage {
            get {
                return this.salaryOrWageField;
            }
            set {
                this.salaryOrWageField = value;
                this.RaisePropertyChanged("SalaryOrWage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string SupervisorEIN {
            get {
                return this.supervisorEINField;
            }
            set {
                this.supervisorEINField = value;
                this.RaisePropertyChanged("SupervisorEIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string ConstructorMessage {
            get {
                return this.constructorMessageField;
            }
            set {
                this.constructorMessageField = value;
                this.RaisePropertyChanged("ConstructorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int RevNum {
            get {
                return this.revNumField;
            }
            set {
                this.revNumField = value;
                this.RaisePropertyChanged("RevNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpInfoServiceSoapChannel : Homework4.EIS.EmpInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpInfoServiceSoapClient : System.ServiceModel.ClientBase<Homework4.EIS.EmpInfoServiceSoap>, Homework4.EIS.EmpInfoServiceSoap {
        
        public EmpInfoServiceSoapClient() {
        }
        
        public EmpInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Homework4.EIS.Employee getEmployee(string EIN, string Token) {
            return base.Channel.getEmployee(EIN, Token);
        }
        
        public System.Threading.Tasks.Task<Homework4.EIS.Employee> getEmployeeAsync(string EIN, string Token) {
            return base.Channel.getEmployeeAsync(EIN, Token);
        }
        
        public string saveEmployee(Homework4.EIS.Employee EmployeeToSave, string strToken) {
            return base.Channel.saveEmployee(EmployeeToSave, strToken);
        }
        
        public System.Threading.Tasks.Task<string> saveEmployeeAsync(Homework4.EIS.Employee EmployeeToSave, string strToken) {
            return base.Channel.saveEmployeeAsync(EmployeeToSave, strToken);
        }
        
        public string saveNewEmployee(Homework4.EIS.Employee EmployeeToSave, string strToken) {
            return base.Channel.saveNewEmployee(EmployeeToSave, strToken);
        }
        
        public System.Threading.Tasks.Task<string> saveNewEmployeeAsync(Homework4.EIS.Employee EmployeeToSave, string strToken) {
            return base.Channel.saveNewEmployeeAsync(EmployeeToSave, strToken);
        }
        
        public string deleteEmployee(string strEIN, string strToken) {
            return base.Channel.deleteEmployee(strEIN, strToken);
        }
        
        public System.Threading.Tasks.Task<string> deleteEmployeeAsync(string strEIN, string strToken) {
            return base.Channel.deleteEmployeeAsync(strEIN, strToken);
        }
        
        public System.Data.DataTable getEmployeesList() {
            return base.Channel.getEmployeesList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getEmployeesListAsync() {
            return base.Channel.getEmployeesListAsync();
        }
        
        public System.Data.DataTable getStatesList() {
            return base.Channel.getStatesList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getStatesListAsync() {
            return base.Channel.getStatesListAsync();
        }
        
        public string logIn(string strUsername, string strPassword) {
            return base.Channel.logIn(strUsername, strPassword);
        }
        
        public System.Threading.Tasks.Task<string> logInAsync(string strUsername, string strPassword) {
            return base.Channel.logInAsync(strUsername, strPassword);
        }
        
        public string logOut(string strToken) {
            return base.Channel.logOut(strToken);
        }
        
        public System.Threading.Tasks.Task<string> logOutAsync(string strToken) {
            return base.Channel.logOutAsync(strToken);
        }
        
        public System.Data.DataTable getDeptList() {
            return base.Channel.getDeptList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDeptListAsync() {
            return base.Channel.getDeptListAsync();
        }
        
        public string changePassword(string username, string pw, string token) {
            return base.Channel.changePassword(username, pw, token);
        }
        
        public System.Threading.Tasks.Task<string> changePasswordAsync(string username, string pw, string token) {
            return base.Channel.changePasswordAsync(username, pw, token);
        }
    }
}
