//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Homework9.NRVVref {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NRVVserviceSoap", Namespace="http://www.radford.edu/NRVV")]
    public partial class NRVVservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTransOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMembersListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatesListOperationCompleted;
        
        private System.Threading.SendOrPostCallback logInOperationCompleted;
        
        private System.Threading.SendOrPostCallback logOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback changePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NRVVservice() {
            this.Url = global::Homework9.Properties.Settings.Default.Homework9_NRVVref_NRVVservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getMemberCompletedEventHandler getMemberCompleted;
        
        /// <remarks/>
        public event getTransCompletedEventHandler getTransCompleted;
        
        /// <remarks/>
        public event saveMemberCompletedEventHandler saveMemberCompleted;
        
        /// <remarks/>
        public event getMembersListCompletedEventHandler getMembersListCompleted;
        
        /// <remarks/>
        public event getStatesListCompletedEventHandler getStatesListCompleted;
        
        /// <remarks/>
        public event logInCompletedEventHandler logInCompleted;
        
        /// <remarks/>
        public event logOutCompletedEventHandler logOutCompleted;
        
        /// <remarks/>
        public event changePasswordCompletedEventHandler changePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.radford.edu/NRVV/getMember", RequestNamespace="http://www.radford.edu/NRVV", ResponseNamespace="http://www.radford.edu/NRVV", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Member getMember(string Username, string Token) {
            object[] results = this.Invoke("getMember", new object[] {
                        Username,
                        Token});
            return ((Member)(results[0]));
        }
        
        /// <remarks/>
        public void getMemberAsync(string Username, string Token) {
            this.getMemberAsync(Username, Token, null);
        }
        
        /// <remarks/>
        public void getMemberAsync(string Username, string Token, object userState) {
            if ((this.getMemberOperationCompleted == null)) {
                this.getMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMemberOperationCompleted);
            }
            this.InvokeAsync("getMember", new object[] {
                        Username,
                        Token}, this.getMemberOperationCompleted, userState);
        }
        
        private void OngetMemberOperationCompleted(object arg) {
            if ((this.getMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMemberCompleted(this, new getMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.radford.edu/NRVV/getTrans", RequestNamespace="http://www.radford.edu/NRVV", ResponseNamespace="http://www.radford.edu/NRVV", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getTrans(string Username, string Token) {
            object[] results = this.Invoke("getTrans", new object[] {
                        Username,
                        Token});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getTransAsync(string Username, string Token) {
            this.getTransAsync(Username, Token, null);
        }
        
        /// <remarks/>
        public void getTransAsync(string Username, string Token, object userState) {
            if ((this.getTransOperationCompleted == null)) {
                this.getTransOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTransOperationCompleted);
            }
            this.InvokeAsync("getTrans", new object[] {
                        Username,
                        Token}, this.getTransOperationCompleted, userState);
        }
        
        private void OngetTransOperationCompleted(object arg) {
            if ((this.getTransCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTransCompleted(this, new getTransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.radford.edu/NRVV/saveMember", RequestNamespace="http://www.radford.edu/NRVV", ResponseNamespace="http://www.radford.edu/NRVV", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string saveMember(Member MemberToSave, string strToken) {
            object[] results = this.Invoke("saveMember", new object[] {
                        MemberToSave,
                        strToken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveMemberAsync(Member MemberToSave, string strToken) {
            this.saveMemberAsync(MemberToSave, strToken, null);
        }
        
        /// <remarks/>
        public void saveMemberAsync(Member MemberToSave, string strToken, object userState) {
            if ((this.saveMemberOperationCompleted == null)) {
                this.saveMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveMemberOperationCompleted);
            }
            this.InvokeAsync("saveMember", new object[] {
                        MemberToSave,
                        strToken}, this.saveMemberOperationCompleted, userState);
        }
        
        private void OnsaveMemberOperationCompleted(object arg) {
            if ((this.saveMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveMemberCompleted(this, new saveMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.radford.edu/NRVV/getMembersList", RequestNamespace="http://www.radford.edu/NRVV", ResponseNamespace="http://www.radford.edu/NRVV", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getMembersList() {
            object[] results = this.Invoke("getMembersList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getMembersListAsync() {
            this.getMembersListAsync(null);
        }
        
        /// <remarks/>
        public void getMembersListAsync(object userState) {
            if ((this.getMembersListOperationCompleted == null)) {
                this.getMembersListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMembersListOperationCompleted);
            }
            this.InvokeAsync("getMembersList", new object[0], this.getMembersListOperationCompleted, userState);
        }
        
        private void OngetMembersListOperationCompleted(object arg) {
            if ((this.getMembersListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMembersListCompleted(this, new getMembersListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.radford.edu/NRVV/getStatesList", RequestNamespace="http://www.radford.edu/NRVV", ResponseNamespace="http://www.radford.edu/NRVV", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getStatesList() {
            object[] results = this.Invoke("getStatesList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getStatesListAsync() {
            this.getStatesListAsync(null);
        }
        
        /// <remarks/>
        public void getStatesListAsync(object userState) {
            if ((this.getStatesListOperationCompleted == null)) {
                this.getStatesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatesListOperationCompleted);
            }
            this.InvokeAsync("getStatesList", new object[0], this.getStatesListOperationCompleted, userState);
        }
        
        private void OngetStatesListOperationCompleted(object arg) {
            if ((this.getStatesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatesListCompleted(this, new getStatesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.radford.edu/NRVV/logIn", RequestNamespace="http://www.radford.edu/NRVV", ResponseNamespace="http://www.radford.edu/NRVV", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string logIn(string strUsername, string strPassword) {
            object[] results = this.Invoke("logIn", new object[] {
                        strUsername,
                        strPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void logInAsync(string strUsername, string strPassword) {
            this.logInAsync(strUsername, strPassword, null);
        }
        
        /// <remarks/>
        public void logInAsync(string strUsername, string strPassword, object userState) {
            if ((this.logInOperationCompleted == null)) {
                this.logInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogInOperationCompleted);
            }
            this.InvokeAsync("logIn", new object[] {
                        strUsername,
                        strPassword}, this.logInOperationCompleted, userState);
        }
        
        private void OnlogInOperationCompleted(object arg) {
            if ((this.logInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logInCompleted(this, new logInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.radford.edu/NRVV/logOut", RequestNamespace="http://www.radford.edu/NRVV", ResponseNamespace="http://www.radford.edu/NRVV", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string logOut(string strToken) {
            object[] results = this.Invoke("logOut", new object[] {
                        strToken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void logOutAsync(string strToken) {
            this.logOutAsync(strToken, null);
        }
        
        /// <remarks/>
        public void logOutAsync(string strToken, object userState) {
            if ((this.logOutOperationCompleted == null)) {
                this.logOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogOutOperationCompleted);
            }
            this.InvokeAsync("logOut", new object[] {
                        strToken}, this.logOutOperationCompleted, userState);
        }
        
        private void OnlogOutOperationCompleted(object arg) {
            if ((this.logOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logOutCompleted(this, new logOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.radford.edu/NRVV/changePassword", RequestNamespace="http://www.radford.edu/NRVV", ResponseNamespace="http://www.radford.edu/NRVV", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string changePassword(string username, string pw, string token) {
            object[] results = this.Invoke("changePassword", new object[] {
                        username,
                        pw,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void changePasswordAsync(string username, string pw, string token) {
            this.changePasswordAsync(username, pw, token, null);
        }
        
        /// <remarks/>
        public void changePasswordAsync(string username, string pw, string token, object userState) {
            if ((this.changePasswordOperationCompleted == null)) {
                this.changePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangePasswordOperationCompleted);
            }
            this.InvokeAsync("changePassword", new object[] {
                        username,
                        pw,
                        token}, this.changePasswordOperationCompleted, userState);
        }
        
        private void OnchangePasswordOperationCompleted(object arg) {
            if ((this.changePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changePasswordCompleted(this, new changePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/NRVV")]
    public partial class Member {
        
        private string usernameField;
        
        private string uSATFnumField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string cellPhoneField;
        
        private string homePhoneField;
        
        private string emailField;
        
        private string proofOfInsField;
        
        private decimal balanceDueField;
        
        private string momFirstNameField;
        
        private string momLastNameField;
        
        private string momCellPhoneField;
        
        private string dadFirstNameField;
        
        private string dadLastNameField;
        
        private string dadCellPhoneField;
        
        private System.DateTime dOBField;
        
        private string constructorMessageField;
        
        private int revNumField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string USATFnum {
            get {
                return this.uSATFnumField;
            }
            set {
                this.uSATFnumField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhone {
            get {
                return this.cellPhoneField;
            }
            set {
                this.cellPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string ProofOfIns {
            get {
                return this.proofOfInsField;
            }
            set {
                this.proofOfInsField = value;
            }
        }
        
        /// <remarks/>
        public decimal BalanceDue {
            get {
                return this.balanceDueField;
            }
            set {
                this.balanceDueField = value;
            }
        }
        
        /// <remarks/>
        public string MomFirstName {
            get {
                return this.momFirstNameField;
            }
            set {
                this.momFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MomLastName {
            get {
                return this.momLastNameField;
            }
            set {
                this.momLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string MomCellPhone {
            get {
                return this.momCellPhoneField;
            }
            set {
                this.momCellPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string DadFirstName {
            get {
                return this.dadFirstNameField;
            }
            set {
                this.dadFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string DadLastName {
            get {
                return this.dadLastNameField;
            }
            set {
                this.dadLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string DadCellPhone {
            get {
                return this.dadCellPhoneField;
            }
            set {
                this.dadCellPhoneField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        public string ConstructorMessage {
            get {
                return this.constructorMessageField;
            }
            set {
                this.constructorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int RevNum {
            get {
                return this.revNumField;
            }
            set {
                this.revNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getMemberCompletedEventHandler(object sender, getMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Member Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Member)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getTransCompletedEventHandler(object sender, getTransCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTransCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTransCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void saveMemberCompletedEventHandler(object sender, saveMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getMembersListCompletedEventHandler(object sender, getMembersListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMembersListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMembersListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getStatesListCompletedEventHandler(object sender, getStatesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void logInCompletedEventHandler(object sender, logInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void logOutCompletedEventHandler(object sender, logOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void changePasswordCompletedEventHandler(object sender, changePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591